# Generated by Django 4.2.1 on 2023-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(choices=[('JEAN', 'JEAN'), ('JEANNE', 'JEANNE'), ('JOHN', 'JOHN')], max_length=255)),
                ('slot_type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
